const CTH_Heads = [
  {
    Head_name: "Web Heads",
    data: [
      {
        name: "Sahil Keshao Lede",
        img: "",
        twe: "",
        insta: "https://www.instagram.com/sahil._k_.lede/",
        fb: "https://www.facebook.com/sahil.lede.3",
        li: "https://www.linkedin.com/in/sahil-lede-092360214",
      },
      { name: "Himanshu Ranjan", img: "", twe: "", insta: "", fb: "", li: "" },
      {
        name: "Vishal Patel",
        img: "",
        twe: "",
        insta: "https://www.instagram.com/vshal007/",
        fb: "https://www.facebook.com/profile.php?id=100055356487184",
        li: "https://www.linkedin.com/in/vishal-patel-536b321a1/",
      },
    ],
  },
  {
    Head_name: "Sponser Heads",
    data: [
      {
        name: "Raunak Jhunjhunwala",
        img: "",
        twe: "",
        insta: "",
        fb: "",
        li: "",
      },
      {
        name: "Satyam Kumar",
        img: "",
        twe: "",
        insta: "https://www.instagram.com/satyam_16_09/",
        fb: "https://www.facebook.com/profile.php?id=100008159530339",
        li: "https://www.linkedin.com/in/satyam-kumar-193a99235/",
      },
      { name: "Janhvi Haldvania", img: "", twe: "", insta: "", fb: "", li: "" },
      {
        name: "Vidyasagar",
        img: "",
        twe: "https://twitter.com/RvsrVidyasagar",
        insta: "https://www.instagram.com/vidyasagar___rvsr/",
        fb: "https://www.facebook.com/vidyasagar.rvsr",
        li: "https://www.linkedin.com/in/vidyasagar-r-92932518b/",
      },
    ],
  },
  {
    Head_name: "Event Heads",
    data: [
      {
        name: "Aman Goswami",
        img: "",
        twe: "",
        insta: "",
        fb: "https://www.facebook.com/profile.php?id=100058652051714&mibextid=ZbWKwL",
        li: "https://www.linkedin.com/in/aman-goswami-470282248",
      },
      {
        name: "Vyde Siddhartha",
        img: "",
        twe: "",
        insta: "https://www.instagram.com/invites/contact/?i=1n7jv2aucybv8&utm_content=44e17tq",
        fb: "https://www.facebook.com/profile.php?id=100013998360562&mibextid=ZbWKwL",
        li: "https://www.linkedin.com/in/vyde-siddhartha-a6116a201",
      },
      {
        name: "Emmadi Manasvi",
        img: "",
        twe: "",
        insta: "",
        fb: "https://www.facebook.com/manasvi.emmadi?mibextid=ZbWKwL",
        li: "https://www.linkedin.com/in/manasvi-emmadi-05425320b/",
      },
      {
        name: "Amgoth Jithender Kumar Naik",
        img: "",
        twe: "",
        insta: "",
        fb: "",
        li: "",
      },
    ],
  },
  {
    Head_name: "Publicity Heads",
    data: [
      { name: "Aditya Raj", img: "", twe: "", insta: "", fb: "", li: "" },
      {
        name: "Anoop Singh",
        img: "",
        twe: "",
        insta: "https://www.instagram.com/anoopsingh_1/",
        fb: "https://www.facebook.com/profile.php?id=100009072704649&mibextid=ZbWKwL",
        li: "https://www.linkedin.com/in/anoop-singh-a9a988200",
      },
      {
        name: "Niharika Singh",
        img: "",
        twe: "",
        insta: "https://www.instagram.com/niharikasingh0208/",
        fb: "https://www.facebook.com/profile.php?id=100059521434357",
        li: "https://www.linkedin.com/in/niharika-singh-49133a223",
      },
      { name: "Tanishq Agarwal", img: "", twe: "", insta: "", fb: "", li: "" },
    ],
  },
  {
    Head_name: "Design Heads",
    data: [
      {
        name: "Shiwangi Prakash",
        img: "",
        twe: "",
        insta: "https://www.instagram.com/shiwangi_prakash_/",
        fb: "https://www.facebook.com/profile.php?id=100085210257327&mibextid=ZbWKwL",
        li: "",
      },
      {
        name: "Chitram Om Sri Vasthav",
        img: "",
        twe: "",
        insta: "https://www.instagram.com/invites/contact/?i=1wr6z23305w06&utm_content=6qq1kuw",
        fb: "https://www.facebook.com/chitram.omsri",
        li: "https://www.linkedin.com/in/chitram-om-sri-vasthav-53222a246",
      },
      {
        name: "Kadali Sri Tulasi",
        img: "",
        twe: "",
        insta: "",
        fb: "",
        li: "",
      },
    ],
  },
];

export default CTH_Heads;
